### ISSUE TITLE
Please add a screenshot and consider renaming this repository

### ISSUE THREAD

**Issue by unixorn** [r3nic1e/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but zsh-theme is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Also, please add a screen shot so people can see what it looks like without having to install it.

Thanks!

**Comment by r3nic1e** [comment]
Thanks! Just created repo to sync my theme between computers.

Renamed repository and added more description with screenshots
